include "base.conf"

slick.dbs {
  default {
    db.properties.url=${DATABASE_URL}
    db.characterEncoding="utf8"
    db.useUnicode=true
    db.numThreads=5
    db.minThreads=5
    db.maxThreads=5
    db.maxConnections=5
    db.queueSize=1000
  }
}
play.evolutions.autoApply=true

play.http.secret.key=${COOKIE_SECRET_KEY}
http.port=80
http.port=${?HTTP_PORT}
https.port=443
http.port=${?HTTPS_PORT}

play.server.https.engineProvider="framework.SslEngineProvider"

play.filters.enabled += framework.RedirectHttpsFilter
play.filters.https.redirectStatusCode = 301

app.domain=${APP_DOMAIN}
